"""added crops and alert tables

Revision ID: d9cc8f42156e
Revises: 17377882c4b0
Create Date: 2024-06-27 10:01:43.521995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd9cc8f42156e'
down_revision: Union[str, None] = '17377882c4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_time_delta', sa.Float(), nullable=True),
    sa.Column('moist_min', sa.Float(), nullable=True),
    sa.Column('moist_max', sa.Float(), nullable=True),
    sa.Column('moist_time_delta', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('parcel_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'address')
    op.add_column('users', sa.Column('email_alert', sa.Boolean()))
    op.add_column('users', sa.Column('sms_alert', sa.Boolean()))
    op.drop_column('parcels', 'size')
    op.add_column('parcels', sa.Column('crop_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_parcels_crops', 'parcels', 'crops', ['crop_id'], ['id'], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('crops')
    op.drop_column('users', 'email_alert')
    op.drop_column('users', 'sms_alert')
    op.drop_column('parcels', 'crop_id')
    op.drop_constraint('fk_parcels_crop', 'parcels', type_='foreignkey')
    # ### end Alembic commands ###
